<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<link rel="stylesheet" href="Layout.css">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>HTML Image Links</title>
</head>
<body>


<header>
eduOnline
</header>

<h1>HTML IMAGE LINKS</h1>


<p>We have seen how to create hypertext link using text and we also learnt how to use images in our webpages. Now we will learn how to use images to create hyperlinks.</p>
<h3>Example</h3>
<p>It's simple to use an image as hyperlink.  We just need to use an image inside  hyperlink at the place of text as shown below:</p>
<pre class="prettyprint notranslate tryit">
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;Image Hyperlink Example&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click following link&lt;/p&gt;
&lt;a href="http://www.tutorialspoint.com" target="_self"&gt; 
   &lt;img src="/images/logo.png" alt="Tutorials Point" border="0"/&gt; 
&lt;/a&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>
<p>This will produce following result, where you can click on the images to reach to the home page of Tutorials Point.</p>
<div class="result notranslate">
<p>Click following link</p>
<a href="http://www.tutorialspoint.com" target="_self"> 
   <img src=".\Images\logo.png" alt="Tutorials Point" style="border:0px"/> 
</a>
</div>
<p>This was the simplest way of creating hyperlinks using images. Next we will see how we can create Mouse-Sensitive Image Links.</p>
<h2>Mouse-Sensitive Images</h2>
<p>The HTML and XHTML standards provide a feature that lets you embed many different links inside a single image. You can create different links on the single image based on different coordinates available on the image.  Once different are links attached to different coordinates, we can click different parts of the image to open target documents. Such mouse-sensitive images are known as image maps.</p>
<p>There are two ways to create image maps:</p>
<ul class="list">
<li><b>Sserver-side image maps -</b> This is enabled by the <b>ismap</b> attribute of the &lt;img&gt; tag and requires access to a server and related image-map processing applications.</li>
<li><b>Client-side image maps -</b> This is created with the <b>usemap</b> attribute of the &lt;img&gt; tag, along with corresponding &lt;map&gt; and &lt;area&gt; tags.</p></li>
</ul>
<h2>Server-Side Image Maps</h2>
<p>Here you simply put your image inside a hyper link and use <b>ismap</b> attribute which makes it special image and when the user clicks some place within the image, the browser passes the coordinates of the mouse pointer along with the URL specified in the &lt;a&gt; tag to the web server. The server uses the mouse-pointer coordinates to determine which document to deliver back to the browser.</p>
<p>When <i>ismap</i> is used, the href attribute of the containing &lt;a&gt; tag must contain the URL of a server application like a cgi or PHP script etc. to process the incoming request based on the passed coordinates.</p>
<p>The coordinates of the mouse position are screen pixels counted from the upper-left corner of the image, beginning with (0,0). The coordinates, preceded by a question mark, are added to the end of the URL.</p>
<p>For example, if a user clicks 20 pixels over and 30 pixels down from the upper-left corner of the following image:</p>
<div class="result notranslate">
<p>Click following link</p>
<a href="/cgi-bin/ismap.cgi" target="_blank"> 
   <img ismap src=".\Images\logo.png" alt="Tutorials Point" style="border:0px"/> 
</a>
</div>
<p>Which has been generated by the following code snippet:</p>
<pre class="prettyprint notranslate tryit">
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;ISMAP Hyperlink Example&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Click following link&lt;/p&gt;
&lt;a href="/cgi-bin/ismap.cgi" target="_self"&gt; 
   &lt;img ismap src="/images/logo.png" alt="Tutorials Point" border="0"/&gt; 
&lt;/a&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>
<p>Then the browser sends the following search parameters to the web server which can be processed by <b>ismap.cgi</b> script or <b>map file</b> and you can link whatever documents you like to these coordinates:</p>
<pre class="prettyprint notranslate">
/cgi-bin/ismap.cgi?20,30
</pre>
<p>This way you can assign different links to different coordinates of the image and when those coordinates are clicked, you can open corresponding linked document. To learn more about <b>ismap</b> attribute, you can check <a href="/html/using_html_ismap.htm"><b>How to use Image ismap?</b></a></p>
<blockquote><b>Note: </b>You will learn CGI programming when you will study Perl programming. You can write your script to process these passed coordinates using PHP or any other script as well. For now let's concentrate on learning HTML and later you can revisit this section.</blockquote>
<h2>Client-Side Image Maps</h2>
<p>Client side image maps are enabled by the <b>usemap</b> attribute of the &lt;img /&gt; tag and defined by special &lt;map&gt; and &lt;area&gt; extension tags.</p>
<p>The image that is going to form the map is inserted into the page using the &lt;img /&gt; tag as a normal image, except it carries an extra attribute called <b>usemap</b>. The value of the usemap attribute is the value which will be used in a &lt;map&gt; tag to link map and image tags. The  &lt;map&gt; along with &lt;area&gt; tags define all the image coordinates and corresponding links.</p>
<p>The &lt;area&gt; tag inside the map tag, specifies the shape and the coordinates to define the boundaries of each clickable hotspot available on the image. Here's an example from the image map:</p>
<pre class="prettyprint notranslate tryit">
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;USEMAP Hyperlink Example&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;p&gt;Search and click the hotspot&lt;/p&gt;
&lt;img src=/images/html.gif alt="HTML Map" border="0" usemap="#html"/&gt;
&lt;!-- Create  Mappings --&gt;
&lt;map name="html"&gt;
   &lt;area shape="circle" 
   coords="80,80,20" href="/css/index.htm" alt="CSS Link" target="_self" /&gt;
   &lt;area shape="rect" 
   coords="5,5,40,40" alt="jQuery Link" href="/jquery/index.htm" target="_self" /&gt;
&lt;/map&gt;
&lt;/body&gt;
&lt;/html&gt;
</pre>
<h2>Coordinate System</h2>
<p>The actual value of coords is totally dependent on the shape in question. Here is a summary, to be followed by detailed examples:</p>
<dl>
<dt><b>rect = x<sub>1</sub> , y<sub>1</sub> , x<sub>2</sub> , y<sub>2</sub></b>
</dt><dd><p>x<sub>1</sub> and y<sub>1</sub> are the coordinates of the upper left corner of the rectangle; x<sub>2</sub> and y<sub>2</sub> are the coordinates of the lower right corner.</p>
</dd><dt><b>circle = x<sub>c</sub> , y<sub>c</sub> , radius</b>
</dt><dd><p>x<sub>c</sub> and y<sub>c</sub> are the coordinates of the center of the circle, and radius is the circle's radius.  A circle centered at 200,50 with a radius of 25 would have the attribute <i>coords="200,50,25"</i></p>
</dd><dt><b>poly = x<sub>1</sub> , y<sub>1</sub> , x<sub>2</sub> , y<sub>2</sub> , x<sub>3</sub> , y<sub>3</sub> ,  ... x<sub>n</sub> , y<sub>n</sub></b>
</dt><dd><p>The various x-y pairs define vertices (points) of the polygon, with a "line" being drawn from one point to the next point.  A diamond-shaped polygon with its top point at 20,20 and 40 pixels across at its widest points would have the attribute <i>coords="20,20,40,40,20,60,0,40"</i>.</p>
</dd>
</dl>
<p>All coordinates are relative to the upper-left corner of the image (0,0). Each shape has a related URL.You can use any image software to know the coordinates of different positions.</p>


<br/><br/><br/><br/><br/>



<a href="HTextLinks.jsp">Previous</a>
<a href="HEmailLinks.jsp">Next</a>


<footer>
<pre>eduOnline
<span style="font-family:Times New Roman; font-size: 20px; color:crimson;margin-top:0px;">Accessible Quality Education</span>
<p style="font-size:10px; color:black;"> &#169 2016. All Rights Reserved</p></pre>
</footer>


</body>
</html>